# Generated by Django 5.1.4 on 2024-12-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
    ]
