# Generated by Django 5.1.3 on 2024-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
