# Generated by Django 5.1.4 on 2024-12-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='IklanPromosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_iklan', models.CharField(max_length=100)),
                ('deskripsi_iklan', models.TextField()),
            ],
        ),
    ]
